Repository jenkins-infra/stats.jenkins.io, pull requests merged in 2024-06, with the labels that each got.

#3 feat: add Jenkinsfile
  .tool-versions
  Jenkinsfile
Labels: enhancement

#6 feat: add descriptive table headers for top plugins
  src/components/StatsInDetail/Charts/StatisticsTable.tsx
Labels: enhancement

#8 docs: add local dev instructions
  README.md
Labels: documentation

#5 chore: add updatecli manifest to retrieve nodejs version from packer-images
  updatecli/updatecli.d/nodejs.yaml
  updatecli/values.yaml
Labels: chore

#10 chore: add Jenkinsfile_updatecli
  Jenkinsfile_updatecli
Labels: chore, updatecli

#12 hotfix(updatecli): correct replacement pattern
  updatecli/updatecli.d/nodejs.yaml
Labels: bug, updatecli

#13 fixup: correct preview URL reported in pull requests
  Jenkinsfile
Labels: bug

#18 cleanup: remove commented code
  src/components/Layout/NavBar.tsx
  src/components/PluginTrends/Charts/PluginCardChart.tsx
  src/components/PluginTrends/Layout/PluginDetailModal.tsx
  src/components/StatsInDetail/Charts/ModalGraphs/Plugins.tsx
  src/components/StatsInDetail/Charts/ModalGraphs/TotalExecutors.tsx
  src/components/StatsInDetail/Charts/OverallTrendsChart.tsx
  src/components/StatsInDetail/Layout/Sidebar.tsx
  src/data/statisticsData.ts
  src/hooks/useCSVData.ts
  src/hooks/useFetchAndFilterPlugins.ts
  src/hooks/usePagination.ts
  src/pages/landing-page/index.tsx
  src/theme/theme.ts
  vite.config.ts.timestamp-1716214323141-d36d70fd73402.mjs
Labels: chore

#7 refactor: Responsiveness
  src/components/PluginTrends/Layout/PluginDetailModal.tsx
Labels: bug

#16 feat: use jenkins io components header/footer
  index.html
  package-lock.json
  package.json
  src/components/Layout/Buttons/ForkMeButton.tsx
  src/components/Layout/Buttons/ResetZoomButton.tsx
  src/components/Layout/Footer.tsx
  src/components/Layout/NavBar.tsx
  src/components/StatsInDetail/Charts/GraphModal.tsx
  src/components/StatsInDetail/Charts/JVMChart.tsx
  src/components/StatsInDetail/Charts/StatisticsTable.tsx
  src/custom-elements.d.ts
  src/hooks/usePluginCount.ts
  src/main.tsx
  src/pages/landing-page/index.tsx
  src/pages/plugin-trends/index.tsx
  src/pages/statistics/index.tsx
  src/theme/theme.ts
  src/utils/csvUtils.ts
  src/utils/jsonUtils.ts
Labels: enhancement

#27 chore: add CODEOWNERS
  CODEOWNERS
Labels: chore

#28 chore: update website title
  index.html
Labels: chore

#25 fix: remove sort-by pkg to fix security vulnerabilities
  package-lock.json
  package.json
  src/components/PluginTrends/Layout/PluginDetailModal.tsx
Labels: bug

#26 docs: add preview to README.md
  README.md
Labels: documentation

#24 feat: fix responsiveness
  package-lock.json
  package.json
  src/components/StatsInDetail/Charts/OverallTrendsChart.tsx
  src/components/StatsInDetail/Layout/Sidebar.tsx
  src/main.tsx
  src/pages/landing-page/index.tsx
  src/pages/plugin-trends/index.tsx
  src/pages/statistics/index.tsx
  src/theme/theme.ts
  src/utils/formatDate.ts
Labels: bug

#43 feat: add production deployment stage
  Jenkinsfile
Labels: enhancement

#53 feat: dedicated previews pipeline
  Jenkinsfile
  Jenkinsfile_previews
Labels: enhancement
